name: Android APK (Buildozer)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip git zip unzip openjdk-17-jdk \
            zlib1g-dev libffi-dev libssl-dev libsqlite3-dev liblzma-dev

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython

      - name: Build debug APK
        run: buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: keystone-apk
          path: bin/*.apk
